- hosts: foo
  connection: local
  become: false
  roles:
    - role: foo
      vars:
        node:
          other: "dsa"
    - role: bar
      vars:
        node:
          other: "abc"
          another: "foobar"
